### ISSUE TITLE
[Feature suggestion] Offline playlists

### ISSUE THREAD

**Issue by LazyTarget** [music-assistant/companion#46]
Hi!

How do you look at adding a feature to download tracks to local disk when browsing my playlists in the companion app (for example Windows). If something like this would be possible, then I could complely replace my Spotify premium account.

Kind regards,
Peter

**Comment by arctixdev** [comment]
Hey Peter!

I totally get where you're coming from with your request. However, I must clarify that that Music Assistant doesn't support or encourage downloading tracks from online services that don’t allow it, as it goes against their TOS and is considered piracy. I hope you understand that we need to steer clear of anything even remotely related to piracy.

That being said, it could maybe still be implemented to work with music providers where it wouldn't be considered piracy such as the local, and potentially Jellyfin and Plex music providers. 

Thanks for your understanding, and sorry for any inconvenience.

Kind regards,
Jonathan

**Comment by LazyTarget** [comment]
Hi Jonathan,

Thanks for the quick answer! :)
And I fully understand you distancing the application towards any kind of piracy.

You say that Jellyfin and Plex providers could potentiall allow for offline tracks? Is that something you have considered or is in a _roadmap_ of anykind?

**Comment by vk2him** [comment]
> Hi Jonathan,
> 
> Thanks for the quick answer! :) And I fully understand you distancing the application towards any kind of piracy.
> 
> You say that Jellyfin and Plex providers could potentiall allow for offline tracks? Is that something you have considered or is in a _roadmap_ of anykind?

It's a bit pointless with Plex and Jellyfin as they are simply accessing your music on your own local server - so you could already download the music to your PC by accessing the files directly?

**Comment by LazyTarget** [comment]
True, but there still is the use case of having the companion app on a laptop/tablet during travelling, perhaps when flying or on train commutes where no internet is available. In my case I have a Plex Server on a NAS at home.

But I guess you can handle this use case as is, just need some more work to download and copy over the specific tracks that you want. Does the app require connectivity or can I use it as a media player and listen to local files directly?

**Comment by arctixdev** [comment]
Hey. I mostly just mentioned local, Plex, and Jellyfin to clarify that downloading songs from these providers probably wouldn't go against their terms. Offline playlists aren't on the roadmap right now since there's a lot of other more important stuff that needs to get done first. Plus, making offline playlists work would be a pretty big task because the companion app doesn't handle any metadata, have a database of songs, or anything like that.

You’re right that the benefits of downloading from local/Plex/Jellyfin would be minor since it’s local anyway, though its of course still nice to have, just not really a priority right now. The app doesn’t need an internet connection as such, but it does need to connect to a Music Assistant server, which you could technically run on your laptop when you’re offline.

Also, I’ll be mostly offline from working on the companion app for the next 9 months, except for some occasional maintenance. So I sadly think there isn't going to be much development happening in the near future
